// Scroll-world config for the Forma landing page. Assets live in public/world/.
const v = (n) => `/world/vid/${n}.mp4`;
const vm = (n) => `/world/vid/${n}-m.mp4`;

export const worldConfig = {
  brand: { name: "Forma", href: "#top" },
  cta: { label: "Start a project", href: "#contact" },
  hint: "scroll to fly in",
  diveScroll: 1.3,
  connScroll: 0.9,
  sections: [
    {
      id: "site", label: "The site",
      still: "/world/site.webp", stillMobile: "/world/site-m.webp",
      clip: v("site"), clipMobile: vm("site"),
      accent: "#6f7a5e",
      scroll: 1.5, linger: 0.35,
      eyebrow: "It starts with the ground",
      title: "Every house begins as a plot of land.",
      body: "Where the sun comes from, what the neighbours see, what the ground is made of.",
      tags: ["Site first", "Orientation", "Ground"],
    },
    {
      id: "studio", label: "The studio",
      still: "/world/studio.webp", stillMobile: "/world/studio-m.webp",
      clip: v("studio"), clipMobile: vm("studio"),
      accent: "#c4643b",
      eyebrow: "One architect",
      title: "The first sketch, drawn by hand.",
      body: "A solo practice. The person who draws the first line is the one who answers the phone.",
      tags: ["Card models", "Hand drawn"],
    },
    {
      id: "detail", label: "The detail",
      still: "/world/detail.webp", stillMobile: "/world/detail-m.webp",
      clip: v("detail"), clipMobile: vm("detail"),
      accent: "#6b645b",
      eyebrow: "Fewer, better materials",
      title: "Every joint, drawn by the same hand.",
      body: "Timber, lime render, stone and steel. A few honest materials, used well, left to age.",
      tags: ["Timber", "Lime render", "Stone"],
    },
    {
      id: "build", label: "The build",
      still: "/world/build.webp", stillMobile: "/world/build-m.webp",
      clip: v("build"), clipMobile: vm("build"),
      accent: "#c4643b",
      eyebrow: "On site until the last day",
      title: "The same person checks the last detail.",
      body: "Through construction, on the phone when the builder calls.",
      tags: ["Site visits", "One point of contact"],
    },
    {
      id: "house", label: "The house",
      still: "/world/house.webp", stillMobile: "/world/house-m.webp",
      clip: v("house"), clipMobile: vm("house"),
      accent: "#3b322c",
      scroll: 1.7, linger: 0.45,
      eyebrow: "Built to belong",
      title: "A home that looks like it was always meant to be there.",
      body: "Houses first. Then workplaces, interiors and the landscape around them.",
      tags: [],
      cta: {
        primary: { label: "Start a project", href: "#contact" },
        secondary: { label: "About the practice", href: "#about" },
      },
    },
  ],
  connectors: [v("conn1"), v("conn2"), v("conn3"), v("conn4")],
  connectorsMobile: [vm("conn1"), vm("conn2"), vm("conn3"), vm("conn4")],
};
